<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="unittest/loader.py" name="unittest.loader._FailedTest-20191116150641" skipped="0" tests="1" time="0.008" timestamp="2019-11-16T15:06:41">
	<testcase classname="unittest.loader._FailedTest" file="..\..\appdata\local\programs\python\python37\lib\unittest\loader.py" line="33" name="hello_tests" time="0.008" timestamp="2019-11-16T15:06:41">
		<error message="Failed to import test module: hello_tests
Traceback (most recent call last):
  File &quot;c:\users\vishnu vardhan\appdata\local\programs\python\python37\lib\unittest\loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;c:\users\vishnu vardhan\pycharmprojects\movierecommendationengine\src\unittest\python\hello_tests.py&quot;, line 1, in &lt;module&gt;
    from mockito import mock, verify
ModuleNotFoundError: No module named 'mockito'
" type="ImportError">
<![CDATA[ImportError: Failed to import test module: hello_tests
Traceback (most recent call last):
  File "c:\users\vishnu vardhan\appdata\local\programs\python\python37\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "c:\users\vishnu vardhan\pycharmprojects\movierecommendationengine\src\unittest\python\hello_tests.py", line 1, in <module>
    from mockito import mock, verify
ModuleNotFoundError: No module named 'mockito'

]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
